"use strict";function _createForOfIteratorHelper(a){if("undefined"==typeof Symbol||null==a[Symbol.iterator]){if(Array.isArray(a)||(a=_unsupportedIterableToArray(a))){var b=0,c=function(){};return{s:c,n:function n(){return b>=a.length?{done:!0}:{done:!1,value:a[b++]}},e:function e(a){throw a},f:c}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}var d,e,f=!0,g=!1;return{s:function s(){d=a[Symbol.iterator]()},n:function n(){var a=d.next();return f=a.done,a},e:function e(a){g=!0,e=a},f:function f(){try{f||null==d["return"]||d["return"]()}finally{if(g)throw e}}}}function _slicedToArray(a,b){return _arrayWithHoles(a)||_iterableToArrayLimit(a,b)||_unsupportedIterableToArray(a,b)||_nonIterableRest()}function _nonIterableRest(){throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}function _unsupportedIterableToArray(a,b){if(a){if("string"==typeof a)return _arrayLikeToArray(a,b);var c=Object.prototype.toString.call(a).slice(8,-1);return"Object"===c&&a.constructor&&(c=a.constructor.name),"Map"===c||"Set"===c?Array.from(c):"Arguments"===c||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(c)?_arrayLikeToArray(a,b):void 0}}function _arrayLikeToArray(a,b){(null==b||b>a.length)&&(b=a.length);for(var c=0,d=Array(b);c<b;c++)d[c]=a[c];return d}function _iterableToArrayLimit(a,b){if("undefined"!=typeof Symbol&&Symbol.iterator in Object(a)){var c=[],d=!0,e=!1,f=void 0;try{for(var g,h=a[Symbol.iterator]();!(d=(g=h.next()).done)&&(c.push(g.value),!(b&&c.length===b));d=!0);}catch(a){e=!0,f=a}finally{try{d||null==h["return"]||h["return"]()}finally{if(e)throw f}}return c}}function _arrayWithHoles(a){if(Array.isArray(a))return a}function validateEmail(a){if(!a||"string"!=typeof a)return!1;// Must contain exactly one @
var b=(a.match(/@/g)||[]).length;if(1!==b)return!1;var c=a.split("@"),d=_slicedToArray(c,2),e=d[0],f=d[1];// Local part checks
if(!e||64<e.length)return!1;if(e.startsWith(".")||e.endsWith("."))return!1;if(e.includes(".."))return!1;if(3<(e.match(/\./g)||[]).length)return!1;// New rule: max 3 dots
// Domain checks
if(!f||!f.includes("."))return!1;if(f.startsWith(".")||f.endsWith("."))return!1;if(f.startsWith("-")||f.endsWith("-"))return!1;if(f.includes(".."))return!1;// Validate each domain label
var g,h=f.split("."),i=_createForOfIteratorHelper(h);try{for(i.s();!(g=i.n()).done;){var k=g.value;if(1>k.length||63<k.length)return!1;if(!/^[a-zA-Z0-9-]+$/.test(k))return!1}// TLD must be at least 2 chars and only letters
}catch(a){i.e(a)}finally{i.f()}var j=h[h.length-1];return!(2>j.length)&&/^[a-zA-Z]+$/.test(j)&&!(254<a.length);// Total length check
}function validateName(a){if(!a||"string"!=typeof a)return!1;// Trim and split by whitespace
var b=a.trim().split(/\s+/).filter(function(a){return 0<a.length});// Must have at least one word
if(0===b.length)return!1;// Each word must:
// - Be 2–30 characters long (reasonable name length)
// - Start with a letter
// - Contain only letters
// - Not be all uppercase (reject random gibberish like "aGHyLSOQQNSJVIuPO")
var c,d=_createForOfIteratorHelper(b);try{for(d.s();!(c=d.n()).done;){var e=c.value;if(2>e.length||30<e.length)return!1;if(!/^[a-zA-Z][a-zA-Z]*$/.test(e))return!1;if(e===e.toUpperCase()&&1<e.length)return!1;// Reject ALL CAPS gibberish
}}catch(a){d.e(a)}finally{d.f()}return!0}window.addEventListener("load",function(){// window bar messaging
var a=document.title;window.addEventListener("blur",function(){document.title="Come back!"}),window.addEventListener("focus",function(){document.title=a});// video
var b=document.querySelectorAll("video");b.forEach(function(a){a.defaultMuted=!0,a.muted=!0,a.loop=!0,a.autoplay=!0,a.addEventListener("click",function(a){a.currentTarget.play()}),a.click()});// contact
var c=document.getElementById("contactForm"),d=document.getElementById("submitContact"),f=document.getElementById("formStatus"),g=c.querySelector("#fullName"),h=c.querySelector("#email");c.addEventListener("submit",function(a){a.preventDefault(),d.innerText="Sending...",validateName(g.value)&&validateEmail(h.value)?fetch("https://script.google.com/macros/s/AKfycbzQOF_mWVbxkbhEVYlv4bkQOoNPdmAw2_rQdaKXTFn7w4PlJSqQPUwEqVEHpZ3G0RuT/exec",{method:"POST",body:new FormData(c)}).then(function(){d.style.display="none",f.style.display="block"})["catch"](function(a){d.disabled=!0,d.innerText="Try again later.",console.error("Error!",a.message)}):(d.style.display="none",f.style.display="block")})});
//# sourceMappingURL=contact.js.map