"use strict";window.addEventListener("load",function(){/* ================================================================
         NavBar + Section Nav — vanilla JS behaviour
         ================================================================ */(function(){function a(a){k.forEach(function(b){b===a||(b.setAttribute("aria-expanded","false"),document.getElementById(b.getAttribute("aria-controls")).hidden=!0)})}// ── Mobile drawer open/close ──────────────────────────────────
function b(){i.setAttribute("aria-expanded","true"),i.setAttribute("aria-label","Close menu"),j.hidden=!1,j.style.animation="ds-drawer-in .22s ease",g()}function c(){i.setAttribute("aria-expanded","false"),i.setAttribute("aria-label","Open menu"),j.hidden=!0}// ── Active nav link (hash-based) ──────────────────────────────
function d(){var a=location.hash||"#";h.querySelectorAll(".ds-nav__link, .ds-nav__drawer-link").forEach(function(b){b.classList.toggle("is-active",b.getAttribute("href")===a)})}// Smooth-scroll helper (works around sticky header height)
function f(a){var b=h.offsetHeight+12,c=a.getBoundingClientRect().top+window.scrollY-b;window.scrollTo({top:c,behavior:"smooth"})}// Which drawer panel to show: section panel if any section is visible
function g(){if(0!==r.length){var a=r.some(function(a){var b=a.getBoundingClientRect();return b.top<window.innerHeight&&0<b.bottom});n.hidden=a,o.hidden=!a}}/* ==============================================================
           Expose syncDrawerPanel so openDrawer() can call it
           ============================================================== */function g(){if(0!==r.length){var a=r.some(function(a){var b=a.getBoundingClientRect();return b.top<window.innerHeight&&0<b.bottom});n.hidden=a,o.hidden=!a}}var h=document.getElementById("mainNav"),i=document.getElementById("burgerBtn"),j=document.getElementById("mobileDrawer");// ── Sticky scroll shadow ──────────────────────────────────────
if("true"===h.dataset.sticky){var s=function(){return h.classList.toggle("is-scrolled",4<window.scrollY)};window.addEventListener("scroll",s,{passive:!0}),s()}// ── Desktop dropdowns ─────────────────────────────────────────
var k=h.querySelectorAll(".ds-nav__links .ds-nav__link[aria-haspopup]");k.forEach(function(b){var c=document.getElementById(b.getAttribute("aria-controls"));b.addEventListener("click",function(d){d.stopPropagation();var e="true"===b.getAttribute("aria-expanded");a(b),b.setAttribute("aria-expanded",!e+""),c.hidden=e})}),document.addEventListener("click",function(){return a(null)}),h.addEventListener("click",function(a){return a.stopPropagation()}),document.addEventListener("keydown",function(b){"Escape"===b.key&&a(null)}),i.addEventListener("click",function(){"true"===i.getAttribute("aria-expanded")?c():b()}),window.addEventListener("resize",function(){768<=window.innerWidth&&c()});// ── Mobile accordion sub-menus ────────────────────────────────
var l=j.querySelectorAll(".ds-nav__drawer-toggle");l.forEach(function(a){var b=document.getElementById(a.getAttribute("aria-controls"));a.addEventListener("click",function(){var c="true"===a.getAttribute("aria-expanded");l.forEach(function(c){c===a||(c.setAttribute("aria-expanded","false"),document.getElementById(c.getAttribute("aria-controls")).hidden=!0)}),a.setAttribute("aria-expanded",!c+""),b.hidden=c})}),j.querySelectorAll("a").forEach(function(a){a.addEventListener("click",function(){return c()})}),window.addEventListener("hashchange",d),d();/* ==============================================================
           SECTION NAV
           Discovers all <section data-title>, builds desktop sidebar
           and mobile drawer panel, tracks active section.
           ============================================================== */var m=document.getElementById("sectionNav"),n=document.getElementById("drawerPanelMain"),o=document.getElementById("drawerPanelSections"),p=document.getElementById("drawerSectionLinks"),q=document.getElementById("drawerBackBtn"),r=Array.from(document.querySelectorAll("[data-title]"));// Discover sections
// Auto-assign ids if missing
if(r.forEach(function(a,b){a.id||(a.id="ds-sec-"+b)}),0<r.length){/* ── IntersectionObserver — active state ───────────────────── */var t=function(b){m.querySelectorAll(".ds-section-nav__link").forEach(function(c){c.classList.toggle("is-active",c.dataset.sectionId===b)}),p.querySelectorAll(".ds-nav__drawer-link").forEach(function(c){c.classList.toggle("is-active",c.dataset.sectionId===b)})};// Seed with first section
r.forEach(function(b,c){if(0<c){var a=document.createElement("div");a.className="ds-section-nav__divider",m.appendChild(a)}var d=document.createElement("a");d.href="#"+b.id,d.className="ds-section-nav__link",d.dataset.sectionId=b.id,d.innerHTML="<span class=\"ds-section-nav__dot\"></span>"+"<span class=\"ds-section-nav__label\">".concat(b.dataset.title,"</span>"),d.addEventListener("click",function(a){a.preventDefault(),f(b)}),m.appendChild(d)}),m.classList.add("is-visible"),r.forEach(function(b){var d=document.createElement("a");d.href="#"+b.id,d.className="ds-nav__drawer-link",d.dataset.sectionId=b.id,d.textContent=b.dataset.title,d.addEventListener("click",function(a){a.preventDefault(),c(),setTimeout(function(){return f(b)},130)}),p.appendChild(d)}),q.addEventListener("click",function(){o.hidden=!0,n.hidden=!1}),r[0]&&t(r[0].id);var u=new IntersectionObserver(function(a){// pick the entry nearest the top of the viewport
var b=a.filter(function(a){return a.isIntersecting}).sort(function(c,a){return c.boundingClientRect.top-a.boundingClientRect.top});b.length&&t(b[0].target.id)},{rootMargin:"-20% 0px -60% 0px",threshold:0});r.forEach(function(a){return u.observe(a)})}})()});
//# sourceMappingURL=navbar.js.map